-- 核心建表 SQL 含中文注释
CREATE TABLE IF NOT EXISTS FILE_REGISTRY(file_id INTEGER PRIMARY KEY, path TEXT NOT NULL, sha256 TEXT, size_bytes INTEGER, gz_mtime TEXT, ingested_at TEXT, status TEXT);
CREATE INDEX IF NOT EXISTS idx_file_path ON FILE_REGISTRY(path);
CREATE TABLE IF NOT EXISTS RUN_SESSION(run_id INTEGER PRIMARY KEY, file_id INTEGER, pass_type TEXT, config_json TEXT, started_at TEXT, ended_at TEXT, total_lines INTEGER, preprocessed_lines INTEGER, matched_lines INTEGER, unmatched_lines INTEGER, status TEXT, FOREIGN KEY(file_id) REFERENCES FILE_REGISTRY(file_id));
CREATE INDEX IF NOT EXISTS idx_run_file ON RUN_SESSION(file_id);
CREATE TABLE IF NOT EXISTS MODULE(mod TEXT PRIMARY KEY, description TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS SUBMODULE(smod TEXT PRIMARY KEY, mod TEXT, description TEXT, created_at TEXT, updated_at TEXT, FOREIGN KEY(mod) REFERENCES MODULE(mod));
CREATE INDEX IF NOT EXISTS idx_smod_mod ON SUBMODULE(mod);
CREATE TABLE IF NOT EXISTS REGEX_TEMPLATE(template_id INTEGER PRIMARY KEY, pattern TEXT NOT NULL, sample_log TEXT, normalized_sample TEXT, match_count INTEGER DEFAULT 0, first_seen TEXT, last_seen TEXT, version INTEGER DEFAULT 1, is_active INTEGER DEFAULT 1, semantic_info TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tpl_pattern ON REGEX_TEMPLATE(pattern);
CREATE TABLE IF NOT EXISTS TEMPLATE_HISTORY(history_id INTEGER PRIMARY KEY, template_id INTEGER, pattern TEXT, sample_log TEXT, version INTEGER, created_at TEXT, source TEXT, note TEXT, FOREIGN KEY(template_id) REFERENCES REGEX_TEMPLATE(template_id));
CREATE INDEX IF NOT EXISTS idx_hist_tpl ON TEMPLATE_HISTORY(template_id);
CREATE TABLE IF NOT EXISTS TEMPLATE_APPLICABILITY(app_id INTEGER PRIMARY KEY, template_id INTEGER, mod TEXT, smod TEXT, observed_count INTEGER DEFAULT 0, first_seen_in_ctx TEXT, last_seen_in_ctx TEXT, source TEXT, last_updated TEXT, UNIQUE(template_id, mod, smod, source), FOREIGN KEY(template_id) REFERENCES REGEX_TEMPLATE(template_id));
CREATE INDEX IF NOT EXISTS idx_app_tpl_ctx ON TEMPLATE_APPLICABILITY(template_id, mod, smod);
CREATE TABLE IF NOT EXISTS UNMATCHED_LOG(um_id INTEGER PRIMARY KEY, run_id INTEGER, mod TEXT, smod TEXT, level TEXT, thread_id TEXT, timestamp TEXT, key_text TEXT, raw_log TEXT, buffered INTEGER DEFAULT 0, buffer_id INTEGER, reason TEXT, FOREIGN KEY(run_id) REFERENCES RUN_SESSION(run_id));
CREATE INDEX IF NOT EXISTS idx_unmatch_run ON UNMATCHED_LOG(run_id);
CREATE TABLE IF NOT EXISTS LOG_MATCH_SUMMARY(summary_id INTEGER PRIMARY KEY, run_id INTEGER, template_id INTEGER, mod TEXT, smod TEXT, classification TEXT, level TEXT, thread_id TEXT, first_ts TEXT, last_ts TEXT, line_count INTEGER, UNIQUE(run_id, template_id, mod, smod, classification, level, thread_id), FOREIGN KEY(run_id) REFERENCES RUN_SESSION(run_id), FOREIGN KEY(template_id) REFERENCES REGEX_TEMPLATE(template_id));
CREATE INDEX IF NOT EXISTS idx_sum_keys ON LOG_MATCH_SUMMARY(run_id, template_id, mod, smod);
CREATE TABLE IF NOT EXISTS KEY_TIME_BUCKET(bucket_id INTEGER PRIMARY KEY, run_id INTEGER, template_id INTEGER, mod TEXT, smod TEXT, classification TEXT, level TEXT, thread_id TEXT, bucket_granularity TEXT, bucket_start TEXT, count_in_bucket INTEGER, UNIQUE(run_id, template_id, mod, smod, classification, level, thread_id, bucket_granularity, bucket_start));
CREATE INDEX IF NOT EXISTS idx_bucket_keys ON KEY_TIME_BUCKET(run_id, template_id, mod, smod, bucket_start);
CREATE TABLE IF NOT EXISTS BUFFER_GROUP(buffer_id INTEGER PRIMARY KEY, scope TEXT, mod TEXT, smod TEXT, size_threshold INTEGER, current_size INTEGER, created_at TEXT, status TEXT);
CREATE TABLE IF NOT EXISTS BUFFER_ITEM(item_id INTEGER PRIMARY KEY, buffer_id INTEGER, run_id INTEGER, timestamp TEXT, mod TEXT, smod TEXT, level TEXT, thread_id TEXT, key_text TEXT, raw_log TEXT, FOREIGN KEY(buffer_id) REFERENCES BUFFER_GROUP(buffer_id));
CREATE INDEX IF NOT EXISTS idx_buf_items ON BUFFER_ITEM(buffer_id);
CREATE TABLE IF NOT EXISTS LLM_TASK(llm_task_id INTEGER PRIMARY KEY, buffer_id INTEGER, model TEXT, prompt_version TEXT, started_at TEXT, finished_at TEXT, status TEXT, input_count INTEGER, output_json TEXT, error TEXT, FOREIGN KEY(buffer_id) REFERENCES BUFFER_GROUP(buffer_id));
CREATE TABLE IF NOT EXISTS BUFFER_RESULT(result_id INTEGER PRIMARY KEY, buffer_id INTEGER, llm_task_id INTEGER, template_id INTEGER, occurrences INTEGER, suggested_context TEXT, FOREIGN KEY(buffer_id) REFERENCES BUFFER_GROUP(buffer_id), FOREIGN KEY(llm_task_id) REFERENCES LLM_TASK(llm_task_id), FOREIGN KEY(template_id) REFERENCES REGEX_TEMPLATE(template_id));
CREATE TABLE IF NOT EXISTS SUMMARY_MODULE(mod TEXT PRIMARY KEY, description TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS SUMMARY_SUBMODULE(smod TEXT PRIMARY KEY, mod TEXT, description TEXT, created_at TEXT, updated_at TEXT, FOREIGN KEY(mod) REFERENCES SUMMARY_MODULE(mod));
CREATE TABLE IF NOT EXISTS SUMMARY_REGEX_TEMPLATE(template_id INTEGER PRIMARY KEY, pattern TEXT, sample_log TEXT, normalized_sample TEXT, version INTEGER, is_active INTEGER, semantic_info TEXT, aggregated_at TEXT, total_match_count INTEGER, first_seen_global TEXT, last_seen_global TEXT);
CREATE TABLE IF NOT EXISTS SUMMARY_TEMPLATE_HISTORY(history_id INTEGER PRIMARY KEY, template_id INTEGER, pattern TEXT, sample_log TEXT, version INTEGER, created_at TEXT, FOREIGN KEY(template_id) REFERENCES SUMMARY_REGEX_TEMPLATE(template_id));
CREATE TABLE IF NOT EXISTS SUMMARY_TEMPLATE_APPLICABILITY(app_id INTEGER PRIMARY KEY, template_id INTEGER, mod TEXT, smod TEXT, total_count INTEGER, first_seen_in_ctx TEXT, last_seen_in_ctx TEXT, source TEXT, last_updated TEXT, UNIQUE(template_id, mod, smod, source), FOREIGN KEY(template_id) REFERENCES SUMMARY_REGEX_TEMPLATE(template_id));
